# Generated by Django 5.0.7 on 2024-07-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_init_email_customer_unit_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='unit_email_confirmed',
        ),
        migrations.AddField(
            model_name='customer',
            name='init_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
