# Generated by Django 5.0.7 on 2024-07-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscriptions_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='acitve',
            field=models.BooleanField(default=True),
        ),
    ]
