# Generated by Django 5.0.7 on 2024-07-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscriptions_acitve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='acitve',
            new_name='active',
        ),
    ]
