# Generated by Django 5.0.7 on 2024-07-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_usersubscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
