# Generated by Django 5.0.7 on 2024-07-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_subscriptionsprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsprice',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionsprice',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
