# Generated by Django 5.0.7 on 2024-07-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_alter_subscriptions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionsprice',
            options={'ordering': ['subscription__order', 'order', 'featured', '-updated']},
        ),
    ]
