# Generated by Django 5.0.7 on 2024-07-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_subscriptionsprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsprice',
            name='features',
            field=models.TextField(blank=True, help_text='One line per feature', null=True),
        ),
    ]
