# Generated by Django 5.0.7 on 2024-07-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_subscriptionsprice_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionsprice',
            name='features',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='features',
            field=models.TextField(blank=True, help_text='One line per feature', null=True),
        ),
    ]
