# Generated by Django 5.0.7 on 2024-07-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_subscriptions_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptions',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
