# Generated by Django 5.0.7 on 2024-07-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_usersubscriptions_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptions',
            name='user_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
