# Generated by Django 5.0.7 on 2024-07-24 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_usersubscriptions_user_cancelled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscriptions',
            old_name='subscriptions',
            new_name='subscription',
        ),
    ]
