# Generated by Django 5.0.7 on 2024-07-24 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0020_rename_subscriptions_usersubscriptions_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscriptions',
            old_name='subscription',
            new_name='subscriptions',
        ),
    ]
